Rezepte_Thomas_Tobias/Rezepte_Thomas_Tobias/Models/Recipe.cs
using System;
using System.Collections.Generic;
namespace Rezepte_Thomas_Tobias.Models
{
    public class Recipe
    {
        private int _id;
        public int Id
        {
            get { return _id; }
            set { if (_id >= 0)
                {
                    _id = value;
                } 
            }
        }

        public string Name { get; set; }
        public string Description { get; set; }
        public string Username { get; set; }
        public int CountPeople { get; set; }

        public Recipe () : this (0, "", "", "", 0) { }
        public Recipe(int id, string name, string description, string username, int countPeople)
        {
            this.Id = id;
            this.Name = name;
            this.Description = description;
            this.Username = username;
            this.CountPeople = countPeople; 
        }

        public string User()
        {
            string UserN = Username;
            return UserN; 
        }
    }
}

Rezepte_Thomas_Tobias/Rezepte_Thomas_Tobias/Models/ViewModels/OneRecipeViewModel.cs
using System;
using System.Collections.Generic;
namespace Rezepte_Thomas_Tobias.Models.ViewModels
{
    public class OneRecipeViewModel
    {
        public string Recipe { get; set; }
        public List<Ingredients> Ingredients { get; set; }
        public int ID { get; set; }
        public int CountPeople { get; set; }
        public List<Comments> Comments { get; set; }
        public Comments NewComment { get; set; }
        public string Description { get; set; }


        public OneRecipeViewModel() : this ("", null, 0, 0, null, null, "") { }
        public OneRecipeViewModel(string recipe, List<Ingredients> ingredients, int id, int personen, 
            List<Comments> comments, Comments newComment, string description)
        {
            this.Recipe = recipe;
            this.Ingredients = ingredients;
            this.ID = id;
            this.CountPeople = personen;
            this.Comments = comments;
            this.NewComment = newComment;
            this.Description = description; 
        }

        public override string ToString()
        {
            string IDString = this.ID + ".jpg";
            return IDString;
        }
    }
}

Rezepte_Thomas_Tobias/Rezepte_Thomas_Tobias/Controllers/RecipeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Rezepte_Thomas_Tobias.Models.DB;
using Rezepte_Thomas_Tobias.Models;
using Rezepte_Thomas_Tobias.Models.ViewModels;
using System.Diagnostics;

namespace Rezepte_Thomas_Tobias.Controllers
{
    public class RecipeController : Controller
    {
        IRepositoryRecipe repRecipe;
        List<Recipe> rpList = new List<Recipe>();
        List<Ingredients> igList = new List<Ingredients>(); 

        public ActionResult Index()
        {
            return View ();
        }

        [HttpGet]
        public ActionResult ShowAllRecipes()
        {
            repRecipe = new RepositoryRecipeDB(); 
            try
            {
                repRecipe.Open();
                rpList = repRecipe.GetAllRecipe();
            }
            catch (Exception)
            {
                return View("Message", new Message());
            }
            finally
            {
                repRecipe.Close();
            }
            return View(rpList);
        }

        [HttpGet]
        public ActionResult OneRecipe(int id = 1)
        {
            try
            {
                Recipe oneRecipe;
                repRecipe = new RepositoryRecipeDB();

                repRecipe.Open();
                oneRecipe = repRecipe.GetOneRecipe(id);
                if (oneRecipe != null)
                {
                    OneRecipeViewModel oneRecipeVM = new OneRecipeViewModel();
                    oneRecipeVM.Recipe = oneRecipe.Description;
                    oneRecipeVM.Ingredients = repRecipe.GetAllIngredients(oneRecipe);
                    oneRecipeVM.ID = oneRecipe.Id;
                    oneRecipeVM.CountPeople = oneRecipe.CountPeople;
                    oneRecipeVM.Comments = repRecipe.GetAllComments(oneRecipe);
                    Session["RecipeID"] = oneRecipeVM.ID;

                    return View(oneRecipeVM);
                }
                else { return null; }
            }
            catch (Exception)
            {
                throw; 
            }
            finally
            {
                repRecipe.Close(); 
            }
        }
        [HttpPost]
        public ActionResult OneRecipe(Comments newComment) 
        {
            try
            {
                if (newComment.Comment != null)
                {
                    repRecipe = new RepositoryRecipeDB();
                    if (Session["loggedUser"] == null)
                    {
                        return RedirectToAction("../User/Authenticate");
                    }
                    if (Session["RecipeID"] == null)
                    {
                        return RedirectToAction("OneRecipe");
                    }
                    newComment.RecipeID = (int)Session["RecipeID"];
                    newComment.UserID = (int)Session["loggedUser"];
                    repRecipe.Open();
                    repRecipe.SaveNewComment(newComment);
                    return RedirectToAction("OneRecipe");

                }
                else
                {
                    return RedirectToAction("OneRecipe");
                }
            }
            catch (Exception)
            {
                throw;
            }
            finally
            {
                repRecipe.Close(); 
            }
        }
        [HttpPost]
        public ActionResult DeleteComment(int commentID)
        {
            try
            {
                repRecipe = new RepositoryRecipeDB();
                repRecipe.Open();
                repRecipe.DeleteComment(commentID);
                int RecipeID = (int)Session["RecipeID"];
                return RedirectToAction("../Recipe/OneRecipe/" + RecipeID);
            }
            catch (Exception)
            {
                throw; 
            }
            finally
            {
                repRecipe.Close(); 
            }

        }
        [HttpPost]
        public ActionResult EditComment(int commentID)
        {
            try
            {
                Recipe oneRecipe; 
                repRecipe = new RepositoryRecipeDB();
                repRecipe.Open();
                oneRecipe = repRecipe.GetOneRecipe((int)Session["RecipeID"]); 
                if (oneRecipe != null)
                {
                    OneRecipeViewModel oneRecipeVM = new OneRecipeViewModel();
                    oneRecipeVM.Recipe = oneRecipe.Description;
                    oneRecipeVM.Ingredients = repRecipe.GetAllIngredients(oneRecipe);
                    oneRecipeVM.ID = oneRecipe.Id;
                    oneRecipeVM.CountPeople = oneRecipe.CountPeople;
                    oneRecipeVM.NewComment = repRecipe.GetOneComment(commentID);
                    return View(oneRecipeVM);
                }
                else { return null; }

            }
            catch(Exception)
            {
                throw;
            }
            finally
            {
                repRecipe.Close(); 
            }
        }
        [HttpPost]
        public ActionResult SaveEditComment(int commentID, string comment)
        {
            try
            {
                if (comment != null)
                {
                    repRecipe = new RepositoryRecipeDB();
                    if (Session["loggedUser"] == null)
                    {
                        return RedirectToAction("../User/Authenticate");
                    }
                    if (Session["RecipeID"] == null)
                    {
                        return RedirectToAction("OneRecipe");
                    }
                    repRecipe.Open();
                    repRecipe.SaveEditComment(comment, commentID);
                    int RecipeID = (int)Session["RecipeID"];
                    return RedirectToAction("../Recipe/OneRecipe/" + RecipeID);

                }
                else
                {
                    return RedirectToAction("OneRecipe");
                }
            }
            catch(Exception)
            {
                throw;
            }
            finally
            {
                repRecipe.Close();
            }
        }
        [HttpGet]
        public ActionResult SaveNewRecipe()
        {
            return View(); 
        }
    }
}

Rezepte_Thomas_Tobias/Rezepte_Thomas_Tobias/Views/Recipe/EditComment.cshtml
@model Rezepte_Thomas_Tobias.Models.ViewModels.OneRecipeViewModel
@using Rezepte_Thomas_Tobias.Models

@{
    ViewBag.Title = "OneRecipe";
}
<span style="display: none" id="count">@Model.CountPeople</span>
<script type="text/javascript">function calculateMenge(o) {
    var val = o.value;
    if (val < 1) {
    o.value = 1;
    }
    else {
            var oldCount = $('#count').html();
            var fields = $('.mengenField');
            fields.each(function() {
                let field = $(this);
                field.html((field.html().trim() / oldCount) * val);
            });
            $('#count').html(val);
    }

    }</script>

<h2>@Model.Recipe</h2>
<table id="ShowOneRecipe">
    <thead>
        <tr>
            <th>Zutaten</th>
            <th>Menge</th>
            <th>Einheit</th>
            <th>
                <img src="~/Media/Images/@Model.ToString()" height=50 width=50 />
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (Ingredients i in Model.Ingredients)
            {
                <tr>
                    <td>
                        @i.Name
                    </td>
                    <td class="mengenField">
                        @i.Menge
                    </td>
                    <td>
                        @i.Einheit
                    </td>

                </tr>
            }
            <tr>
                <td><input type="number" value="@Model.CountPeople" onchange="calculateMenge(this)" /></td>

            </tr>
        }
        else
        {
            <tr>
                <td> Kein Rezept vorhanden!</td>


            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td> <button>@Html.ActionLink("Back", "ShowAllRecipes")</button> </td>
        </tr>
    </tfoot>
</table>
<table>
    <tr>
        <th>Kommentar</th>
        <th></th>
    </tr>
    <tr>
    @if (Model.NewComment.Comment != null)
    {
            using (Html.BeginForm("SaveEditComment", "Recipe", FormMethod.Post))
            {
                    @Html.Hidden("commentID", Model.NewComment.Id);

                    @Html.TextArea("comment", Model.NewComment.Comment, new {cols=40, rows=10});

                    <td>
                        <span style="float:right"><input type="submit" value="Save" /></span>
                    </td>
            }
    }
    </tr>
</table>



Rezepte_Thomas_Tobias/Rezepte_Thomas_Tobias/Views/Recipe/Index.cshtml
@{
    Layout = null;
}

<!DOCTYPE html>
<html>
<head>
</head>
<body>
    hello
</body>
</html>

Rezepte_Thomas_Tobias/Rezepte_Thomas_Tobias/Views/Recipe/OneRecipe.cshtml
@model Rezepte_Thomas_Tobias.Models.ViewModels.OneRecipeViewModel
@using Rezepte_Thomas_Tobias.Models

@{
    ViewBag.Title = "OneRecipe";
}
<span style="display: none" id="count">@Model.CountPeople</span>
<script type="text/javascript">
        function calculateMenge(o) {
    var val = o.value;
    if (val < 1) {
    o.value = 1;
    }
    else {
            var oldCount = $('#count').html();
            var fields = $('.mengenField');
            fields.each(function() {
                let field = $(this);
                field.html((field.html().trim() / oldCount) * val);
            });
            $('#count').html(val);
    }

    }
</script>

<h2>@Model.Recipe</h2>
<table id="ShowOneRecipe">
    <thead>
        <tr>
            <th>Zutaten</th>
            <th>Menge</th>
            <th>Einheit</th>
            <th>
                <img src="~/Media/Images/@Model.ToString()" height=50 width=50 />
            </th>
        </tr>
    </thead>
    <tbody>
        @if (Model != null)
        {
            foreach (Ingredients i in Model.Ingredients)
            {
                <tr>
                    <td>
                        @i.Name
                    </td>
                    <td class="mengenField">
                        @i.Menge
                    </td>
                    <td>
                        @i.Einheit
                    </td>

                </tr>
            }
            <tr>
                <td>Anzahl Personen: <input type="number" value="@Model.CountPeople" onchange="calculateMenge(this)" /></td>

            </tr>
        }
        else
        {
            <tr>
                <td> Kein Rezept vorhanden!</td>


            </tr>
        }
    </tbody>
    <tfoot>
        <tr>
            <td> <button>@Html.ActionLink("Back", "ShowAllRecipes")</button> </td>
        </tr>
    </tfoot>
</table>
<table>
    <tr>
        <th>User</th>
        <th>Kommentar</th>
        <th></th>
    </tr>
    @if (Model.Comments != null)
    {
        foreach (Comments c in Model.Comments)
        {
            <tr>
                <td>
                    @c.Username:
                </td>
                <td>
                    @c.Comment
                </td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td>
                    <span style="float:right">
                        @using (Html.BeginForm("EditComment", "Recipe", FormMethod.Post))
                        {
                            if ((Session["loggedUser"] != null) && (c.UserID == (int)Session["loggedUser"]))
                            {
                                @Html.Hidden("commentID", c.Id);

                                <input type="submit" value="Edit" />


                            }
                        }       
                        @using (Html.BeginForm("DeleteComment", "Recipe", FormMethod.Post))
                        { 
                            if ((Session["loggedUser"] != null) && (c.UserID == (int)Session["loggedUser"]))
                            {
                                @Html.Hidden("commentID", c.Id);

                                <input type="submit" value="Delete" />
                                <br />
                            }
                        }
                        </span>
                    <br />
                </td>
            </tr>
        }
    }
</table>


<br />
@using (Html.BeginForm())
{
    <p>Kommentar schreiben:</p>
    @Html.TextAreaFor(p => p.NewComment.Comment, new {cols=40, rows=10})
    <br />
    <input type="submit" value="Kommentieren" />
}


Rezepte_Thomas_Tobias/Rezepte_Thomas_Tobias/Views/Recipe/SaveNewRecipe.cshtml
@model Rezepte_Thomas_Tobias.Models.ViewModels.OneRecipeViewModel
@using Rezepte_Thomas_Tobias.Models

<!DOCTYPE html>
<html>
    <head>
        <title>SaveNewRecipe</title>
    </head>
<body>

    <script type="text/javascript">
        var rowCount = 0;
                function add_row()
                {
                        var trhtml = document.getElementById( "IngredientsTable" ).insertRow( 1 );
                        trhtml.id = rowCount;
                        var tdhtml1 = document.createElement( "td" );
                        var tdhtml2 = document.createElement( "td" );
                        var tdhtml3 = document.createElement( "td" );
                        var tdhtml4 = document.createElement( "td" );
                        tdhtml1.id = name;
                        tdhtml1.innerHTML = document.getElementById("NameInput").value; // content
                        tdhtml2.innerHTML = document.getElementById("MengeInput").value;
                        tdhtml3.innerHTML = document.getElementById("EinheitInput").value;
                        tdhtml4.innerHTML = '<button id="' + rowCount + '" onclick="deleteRow(this.id)">X</button>';
                        rowCount++;
                        trhtml.appendChild( tdhtml1 );
                        trhtml.appendChild( tdhtml2 );
                        trhtml.appendChild( tdhtml3 );
                        trhtml.appendChild( tdhtml4 );
                        document.getElementById("NameInput").value = '';
                        document.getElementById("MengeInput").value = '';
                        document.getElementById("EinheitInput").value = '';
                }
        function deleteRow(rowid)
        {
            var row = document.getElementById(rowid);
            row.parentNode.removeChild(row);
        }
        function myFunction() {
            for (var i = 0; i < document.getElementById("IngredientsTable").rows.length; i++) {
            alert(document.getElementById("IngredientsTable").rows[i].cells.namedItem("name").innerHTML);
            }
        }

    </script>


    <div class="container-fluid">

        <div style="text-align: center;">

            <div style="display: inline-block;">

                @using (Html.BeginForm("SaveNewRecipe", "Recipe", FormMethod.Post))
                {
                    <p>Rezeptname:</p>
                    @Html.TextBoxFor(p => p.Recipe)
                    <br />
                    <p>Beschreibung:</p>
                    @Html.TextAreaFor(p => p.Description, new { cols = 40, rows = 5 })
                    <p>Zutanten:</p>
                    <table id="IngredientsTable" border="1">
                        <tr>
                            <th>Name</th>
                            <th>Menge</th>
                            <th>Einheit</th>
                        </tr>
                        <tr>
                            <td>
                                <input id="NameInput" type="text" />
                            </td>
                            <td>
                                <input id="MengeInput" type="text" />
                            </td>
                            <td>
                                <input id="EinheitInput" type="text" />
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="button" value="Eintrag hinzufügen" onclick="add_row()" />
                            </td>
                        </tr>
                    </table>
                    <p>Für wie viele Personen:</p>
                    @Html.TextBoxFor(p => p.CountPeople)
                    <br />
                    <input type="submit" value="Posten" />
                }
            </div>

        </div>

    </div>

</body>
</html>



Rezepte_Thomas_Tobias/Rezepte_Thomas_Tobias/Views/Recipe/ShowAllRecipes.cshtml
@model List<Rezepte_Thomas_Tobias.Model.Recipe>
@using Rezepte_Thomas_Tobias.Models

<!DOCTYPE html>

@if ((Model != null) && (Model.Count >= 1))
{
    <table id="AllRecipes">
        <thead>
            <tr>
                <th>ID</th>
                <th>Name</th>
                <th>Description</th>
                <th></th>
                <th>Username</th>
            </tr>
        </thead>
        <tbody>
            @foreach (Recipe r in Model)
            {
            <tr>
                <td>@r.Id</td>
                <td>@r.Name</td>
                <td>@r.Description</td>
                <td> <img src="@string.Format("../Media/Images/{0}.jpg", @r.Id)" height=50 width=50 /> </td>
                <td>@r.Username</td>
                <td> <button>@Html.ActionLink("Details", "OneRecipe/" + @r.Id)</button></td>

            </tr>
            }
        </tbody>
        <tfoot>
        </tfoot>
    </table>
}
else
{
    <p>Keine Rezepte vorhanden!</p>
}